# Form implementation generated from reading ui file 'entry.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Greeting(object):
    def setupUi(self, Greeting):
        Greeting.setObjectName("Greeting")
        Greeting.resize(800, 600)
        Greeting.setFixedSize(800, 600)
        self.tittle = QtWidgets.QLabel(parent=Greeting)
        self.tittle.setGeometry(QtCore.QRect(20, 10, 761, 241))
        font = QtGui.QFont()
        font.setPointSize(55)
        self.tittle.setFont(font)
        self.tittle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.tittle.setObjectName("tittle")
        self.subtittle = QtWidgets.QLabel(parent=Greeting)
        self.subtittle.setGeometry(QtCore.QRect(20, 180, 761, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.subtittle.setFont(font)
        self.subtittle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.subtittle.setObjectName("")
        self.enterBtn = QtWidgets.QPushButton(parent=Greeting)
        self.enterBtn.setGeometry(QtCore.QRect(320, 430, 161, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.enterBtn.setFont(font)
        self.enterBtn.setObjectName("enterBtn")
        self.retranslateUi(Greeting)
        QtCore.QMetaObject.connectSlotsByName(Greeting)

    def retranslateUi(self, Greeting):
        _translate = QtCore.QCoreApplication.translate
        Greeting.setWindowTitle(_translate("Greeting", "Waves simulation"))
        self.tittle.setText(_translate("Greeting", "Waves simulation"))

        self.enterBtn.setText(_translate("Greeting", "Enter"))
        with open("templates/stylesheets/entry.css", "r") as f:
            stylesheet = f.read()
        Greeting.setStyleSheet(stylesheet)

