# Form implementation generated from reading ui file 'load.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Load(object):
    def setupUi(self, Load):
        Load.setObjectName("Load")
        Load.resize(800, 600)
        self.LoadBtn = QtWidgets.QPushButton(parent=Load)
        self.LoadBtn.setGeometry(QtCore.QRect(630, 20, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.LoadBtn.setFont(font)
        self.LoadBtn.setObjectName("pushButton")
        self.listView = QtWidgets.QListView(parent=Load)
        self.listView.setGeometry(QtCore.QRect(20, 30, 581, 541))
        self.listView.setObjectName("listView")
        self.GoBackBtn = QtWidgets.QPushButton(parent=Load)
        self.GoBackBtn.setGeometry(QtCore.QRect(620, 500, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.GoBackBtn.setFont(font)
        self.GoBackBtn.setObjectName("Create_3")

        self.retranslateUi(Load)
        QtCore.QMetaObject.connectSlotsByName(Load)

    def retranslateUi(self, Load):
        _translate = QtCore.QCoreApplication.translate
        Load.setWindowTitle(_translate("Load", "Waves simulation"))
        self.LoadBtn.setText(_translate("Load", "Load"))
        self.GoBackBtn.setText(_translate("Load", "Go back"))
