# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.VisualOutput = QtWidgets.QLabel(parent=self.centralwidget)
        self.VisualOutput.setGeometry(QtCore.QRect(10, 10, 650, 550))
        self.VisualOutput.setText("")
        self.VisualOutput.setObjectName("VisualOutput")
        self.Play_PauseBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Play_PauseBtn.setGeometry(QtCore.QRect(670, 10, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Play_PauseBtn.setFont(font)
        self.Play_PauseBtn.setObjectName("pushButton")
        self.ResetBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ResetBtn.setGeometry(QtCore.QRect(670, 90, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.ResetBtn.setFont(font)
        self.ResetBtn.setObjectName("pushButton_2")
        self.horizontalSlider = QtWidgets.QSlider(parent=self.centralwidget)
        self.horizontalSlider.setGeometry(QtCore.QRect(670, 240, 121, 20))
        self.horizontalSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(670, 190, 111, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.MenuBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.MenuBtn.setGeometry(QtCore.QRect(670, 490, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.MenuBtn.setFont(font)
        self.MenuBtn.setObjectName("pushButton_3")
        self.SaveBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SaveBtn.setGeometry(QtCore.QRect(670, 420, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.SaveBtn.setFont(font)
        self.SaveBtn.setObjectName("pushButton_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wave simulation"))
        self.Play_PauseBtn.setText(_translate("MainWindow", "Pause"))
        self.ResetBtn.setText(_translate("MainWindow", "Reset"))
        self.label.setText(_translate("MainWindow", "Size of brush"))
        self.MenuBtn.setText(_translate("MainWindow", "Menu"))
        self.SaveBtn.setText(_translate("MainWindow", "Save"))
