# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(800, 600)
        Menu.setFixedSize(800, 600)
        self.CreateBtn = QtWidgets.QPushButton(parent=Menu)
        self.CreateBtn.setGeometry(QtCore.QRect(70, 470, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.CreateBtn.setFont(font)
        self.CreateBtn.setObjectName("pushButton_2")
        self.LoadBtn = QtWidgets.QPushButton(parent=Menu)
        self.LoadBtn.setGeometry(QtCore.QRect(470, 470, 271, 91))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.LoadBtn.setFont(font)
        self.LoadBtn.setObjectName("pushButton_3")
        self.label = QtWidgets.QLabel(parent=Menu)
        self.label.setGeometry(QtCore.QRect(87, 57, 641, 141))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Waves simulation"))
        self.CreateBtn.setText(_translate("Menu", "Create new field"))
        self.LoadBtn.setText(_translate("Menu", "Load"))
        self.label.setText(_translate("MeKnu", "Menu"))
        with open("templates/stylesheets/menu.css", "r") as f:
            stylesheet = f.read()
        self.setStyleSheet(stylesheet)
