# Form implementation generated from reading ui file 'save.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Save(object):
    def setupUi(self, Save):
        Save.setObjectName("Save")
        Save.resize(800, 600)
        Save.setFixedSize(800, 600)
        self.SaveBtn = QtWidgets.QPushButton(parent=Save)
        self.SaveBtn.setGeometry(QtCore.QRect(300, 420, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.SaveBtn.setFont(font)
        self.SaveBtn.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(parent=Save)
        self.lineEdit.setGeometry(QtCore.QRect(140, 150, 521, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=Save)
        self.label.setGeometry(QtCore.QRect(270, 220, 291, 31))
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Save)
        self.label_2.setGeometry(QtCore.QRect(150, 40, 521, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.GoBackBtn = QtWidgets.QPushButton(parent=Save)
        self.GoBackBtn.setGeometry(QtCore.QRect(620, 510, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.GoBackBtn.setFont(font)
        self.GoBackBtn.setObjectName("Create_3")
        self.listView = QtWidgets.QListView(parent=Save)
        self.listView.setGeometry(QtCore.QRect(140, 200, 521, 201))
        self.listView.setObjectName("listView")

        self.retranslateUi(Save)
        QtCore.QMetaObject.connectSlotsByName(Save)

    def retranslateUi(self, Save):
        _translate = QtCore.QCoreApplication.translate
        Save.setWindowTitle(_translate("Save", "Waves simulation"))
        self.SaveBtn.setText(_translate("Save", "Save"))
        self.label_2.setText(_translate("Save", "Enter a name for your save"))
        self.GoBackBtn.setText(_translate("Save", "Go back"))
